# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'debb83e008eb4edea148aa21de6adf41'
  config.secret_key = '63032974329af9d9f1a3b4e2a3087e0f'
  config.default_from = 'teamtuba.thp@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
